var output  = [
    {
        "chapter": [
            "https://www.biblegateway.com/passage/?search=Mark+1&version=ESV",
            "https://www.biblegateway.com/passage/?search=Mark+1&version=NVI"
        ],
        "https://www.biblegateway.com/passage/?search=Mark+1&version=ESV": [
            "John the Baptist Prepares the Way",
            "1 The beginning of the gospel of Jesus Christ, the Son of God.[a]",
            "2 As it is written in Isaiah the prophet,[b]",
            "“Behold, I send my messenger before your face,",
            "who will prepare your way,",
            "3 the voice of one crying in the wilderness:",
            "‘Prepare[c] the way of the Lord,",
            "make his paths straight,’”",
            "4 John appeared, baptizing in the wilderness and proclaiming a baptism of repentance for the forgiveness of sins.",
            "5 And all the country of Judea and all Jerusalem were going out to him and were being baptized by him in the river Jordan, confessing their sins.",
            "6 Now John was clothed with camel's hair and wore a leather belt around his waist and ate locusts and wild honey.",
            "7 And he preached, saying, “After me comes he who is mightier than I, the strap of whose sandals I am not worthy to stoop down and untie.",
            "8 I have baptized you with water, but he will baptize you with the Holy Spirit.”",
            "The Baptism of Jesus",
            "9 In those days Jesus came from Nazareth of Galilee and was baptized by John in the Jordan.",
            "10 And when he came up out of the water, immediately he saw the heavens being torn open and the Spirit descending on him like a dove.",
            "11 And a voice came from heaven, “You are my beloved Son;[d] with you I am well pleased.”",
            "The Temptation of Jesus",
            "12 The Spirit immediately drove him out into the wilderness.",
            "13 And he was in the wilderness forty days, being tempted by Satan. And he was with the wild animals, and the angels were ministering to him.",
            "Jesus Begins His Ministry",
            "14 Now after John was arrested, Jesus came into Galilee, proclaiming the gospel of God,",
            "15 and saying, “The time is fulfilled, and the kingdom of God is at hand;[e] repent and believe in the gospel.”",
            "Jesus Calls the First Disciples",
            "16 Passing alongside the Sea of Galilee, he saw Simon and Andrew the brother of Simon casting a net into the sea, for they were fishermen.",
            "17 And Jesus said to them, “Follow me, and I will make you become fishers of men.”[f]",
            "18 And immediately they left their nets and followed him.",
            "19 And going on a little farther, he saw James the son of Zebedee and John his brother, who were in their boat mending the nets.",
            "20 And immediately he called them, and they left their father Zebedee in the boat with the hired servants and followed him.",
            "Jesus Heals a Man with an Unclean Spirit",
            "21 And they went into Capernaum, and immediately on the Sabbath he entered the synagogue and was teaching.",
            "22 And they were astonished at his teaching, for he taught them as one who had authority, and not as the scribes.",
            "23 And immediately there was in their synagogue a man with an unclean spirit. And he cried out,",
            "24 “What have you to do with us, Jesus of Nazareth? Have you come to destroy us? I know who you are—the Holy One of God.”",
            "25 But Jesus rebuked him, saying, “Be silent, and come out of him!”",
            "26 And the unclean spirit, convulsing him and crying out with a loud voice, came out of him.",
            "27 And they were all amazed, so that they questioned among themselves, saying, “What is this? A new teaching with authority! He commands even the unclean spirits, and they obey him.”",
            "28 And at once his fame spread everywhere throughout all the surrounding region of Galilee.",
            "Jesus Heals Many",
            "29 And immediately he[g] left the synagogue and entered the house of Simon and Andrew, with James and John.",
            "30 Now Simon's mother-in-law lay ill with a fever, and immediately they told him about her.",
            "31 And he came and took her by the hand and lifted her up, and the fever left her, and she began to serve them.",
            "32 That evening at sundown they brought to him all who were sick or oppressed by demons.",
            "33 And the whole city was gathered together at the door.",
            "34 And he healed many who were sick with various diseases, and cast out many demons. And he would not permit the demons to speak, because they knew him.",
            "Jesus Preaches in Galilee",
            "35 And rising very early in the morning, while it was still dark, he departed and went out to a desolate place, and there he prayed.",
            "36 And Simon and those who were with him searched for him,",
            "37 and they found him and said to him, “Everyone is looking for you.”",
            "38 And he said to them, “Let us go on to the next towns, that I may preach there also, for that is why I came out.”",
            "39 And he went throughout all Galilee, preaching in their synagogues and casting out demons.",
            "Jesus Cleanses a Leper",
            "40 And a leper[h] came to him, imploring him, and kneeling said to him, “If you will, you can make me clean.”",
            "41 Moved with pity, he stretched out his hand and touched him and said to him, “I will; be clean.”",
            "42 And immediately the leprosy left him, and he was made clean.",
            "43 And Jesus[i] sternly charged him and sent him away at once,",
            "44 and said to him, “See that you say nothing to anyone, but go, show yourself to the priest and offer for your cleansing what Moses commanded, for a proof to them.”",
            "45 But he went out and began to talk freely about it, and to spread the news, so that Jesus could no longer openly enter a town, but was out in desolate places, and people were coming to him from every quarter.",
            "Back "
        ],
        "https://www.biblegateway.com/passage/?search=Mark+1&version=NVI": [
            "Juan el Bautista prepara el camino",
            "1 Comienzo del evangelio de Jesucristo, el Hijo de Dios.[a]",
            "2 Sucedió como está escrito en el profeta Isaías:",
            "«Yo estoy por enviar a mi mensajero delante de ti,",
            "el cual preparará tu camino».[b]",
            "3 «Voz de uno que grita en el desierto:",
            "“Preparen el camino del Señor,",
            "háganle sendas derechas”».[c]",
            "4 Así se presentó Juan, bautizando en el desierto y predicando el bautismo de arrepentimiento para el perdón de pecados. ",
            "5 Toda la gente de la región de Judea y de la ciudad de Jerusalén acudía a él. Cuando confesaban sus pecados, él los bautizaba en el río Jordán. ",
            "6 La ropa de Juan estaba hecha de pelo de camello. Llevaba puesto un cinturón de cuero, y comía langostas y miel silvestre. ",
            "7 Predicaba de esta manera: «Después de mí viene uno más poderoso que yo; ni siquiera merezco agacharme para desatar la correa de sus sandalias. ",
            "8 Yo los he bautizado a ustedes con[d] agua, pero él los bautizará con el Espíritu Santo».",
            "Bautismo y tentación de Jesús",
            "9 En esos días llegó Jesús desde Nazaret de Galilea y fue bautizado por Juan en el Jordán. ",
            "10 En seguida, al subir del agua, Jesús vio que el cielo se abría y que el Espíritu bajaba sobre él como una paloma. ",
            "11 También se oyó una voz del cielo que decía: «Tú eres mi Hijo amado; estoy muy complacido contigo».",
            "12 En seguida el Espíritu lo impulsó a ir al desierto, ",
            "13 y allí fue tentado por Satanás durante cuarenta días. Estaba entre las fieras, y los ángeles le servían.",
            "Llamamiento de los primeros discípulos",
            "14 Después de que encarcelaron a Juan, Jesús se fue a Galilea a anunciar las buenas nuevas de Dios. ",
            "15 «Se ha cumplido el tiempo —decía—. El reino de Dios está cerca. ¡Arrepiéntanse y crean las buenas nuevas!»",
            "16 Pasando por la orilla del mar de Galilea, Jesús vio a Simón y a su hermano Andrés que echaban la red al lago, pues eran pescadores. ",
            "17 «Vengan, síganme —les dijo Jesús—, y los haré pescadores de hombres». ",
            "18 Al momento dejaron las redes y lo siguieron.",
            "19 Un poco más adelante vio a Jacobo y a su hermano Juan, hijos de Zebedeo, que estaban en su barca remendando las redes. ",
            "20 En seguida los llamó, y ellos, dejando a su padre Zebedeo en la barca con los jornaleros, se fueron con Jesús.",
            "Jesús expulsa a un espíritu maligno",
            "21 Entraron en Capernaúm y, tan pronto como llegó el sábado, Jesús fue a la sinagoga y se puso a enseñar. ",
            "22 La gente se asombraba de su enseñanza, porque la impartía como quien tiene autoridad y no como los maestros de la ley. ",
            "23 De repente, en la sinagoga, un hombre que estaba poseído por un espíritu maligno gritó:",
            "24 ―¿Por qué te entrometes, Jesús de Nazaret? ¿Has venido a destruirnos? Yo sé quién eres tú: ¡el Santo de Dios!",
            "25 ―¡Cállate! —lo reprendió Jesús—. ¡Sal de ese hombre!",
            "26 Entonces el espíritu maligno sacudió al hombre violentamente y salió de él dando un alarido. ",
            "27 Todos se quedaron tan asustados que se preguntaban unos a otros: «¿Qué es esto? ¡Una enseñanza nueva, pues lo hace con autoridad! Les da órdenes incluso a los espíritus malignos, y le obedecen». ",
            "28 Como resultado, su fama se extendió rápidamente por toda la región de Galilea.",
            "Jesús sana a muchos enfermos",
            "29 Tan pronto como salieron de la sinagoga, Jesús fue con Jacobo y Juan a casa de Simón y Andrés. ",
            "30 La suegra de Simón estaba en cama con fiebre, y en seguida se lo dijeron a Jesús. ",
            "31 Él se le acercó, la tomó de la mano y la ayudó a levantarse. Entonces se le quitó la fiebre y se puso a servirles.",
            "32 Al atardecer, cuando ya se ponía el sol, la gente le llevó a Jesús todos los enfermos y endemoniados, ",
            "33 de manera que la población entera se estaba congregando a la puerta. ",
            "34 Jesús sanó a muchos que padecían de diversas enfermedades. También expulsó a muchos demonios, pero no los dejaba hablar porque sabían quién era él.",
            "Jesús ora en un lugar solitario",
            "35 Muy de madrugada, cuando todavía estaba oscuro, Jesús se levantó, salió de la casa y se fue a un lugar solitario, donde se puso a orar. ",
            "36 Simón y sus compañeros salieron a buscarlo.",
            "37 Por fin lo encontraron y le dijeron:",
            "―Todo el mundo te busca.",
            "38 Jesús respondió:",
            "―Vámonos de aquí a otras aldeas cercanas donde también pueda predicar; para esto he venido.",
            "39 Así que recorrió toda Galilea, predicando en las sinagogas y expulsando demonios.",
            "Jesús sana a un leproso",
            "40 Un hombre que tenía lepra se le acercó, y de rodillas le suplicó:",
            "―Si quieres, puedes limpiarme.",
            "41 Movido a compasión, Jesús extendió la mano y tocó al hombre, diciéndole:",
            "―Sí, quiero. ¡Queda limpio!",
            "42 Al instante se le quitó la lepra y quedó sano.[e] ",
            "43 Jesús lo despidió en seguida con una fuerte advertencia:",
            "44 ―Mira, no se lo digas a nadie; solo ve, preséntate al sacerdote y lleva por tu purificación lo que ordenó Moisés, para que les sirva de testimonio.",
            "45 Pero él salió y comenzó a hablar sin reserva, divulgando lo sucedido. Como resultado, Jesús ya no podía entrar en ningún pueblo abiertamente, sino que se quedaba afuera, en lugares solitarios. Aun así, gente de todas partes seguía acudiendo a él.",
            "Back "
        ]
    }
]


var _ = require('lodash');

